//+------------------------------------------------------------------+
//|                  cnn_lstm_strategy_Fixed.mq5                     |
//|      Generated by ML Backtester Framework - Copyright 2025       |
//|      Fixed version addressing Error 4806 buffer copying issues   |
//+------------------------------------------------------------------+
#property copyright "Copyright 2025, ML Backtester Framework"
#property link      "https://github.com/your_repo"
#property version   "1.01"
#property strict

#include <Trade\Trade.mqh>
#include <Trade\SymbolInfo.mqh>

//--- EA Inputs
input string InpApiEndpoint = "http://127.0.0.1:5001/predict"; // API Endpoint for predictions
input double InpRiskPerTrade = 0.01;      // Risk per trade
input double InpSLMultiplier = 2.0;       // Stop Loss ATR Multiplier
input double InpTPMultiplier = 3.0;       // Take Profit ATR Multiplier
input int    InpLookBack     = 60;        // Model Look-back period
input int    InpMaxRetries   = 10;        // Maximum retry attempts for data copying
input int    InpRetryDelay   = 200;       // Delay between retries (ms)

//--- Indicator Parameters (must match training)
input int    InpMAPeriod     = 200;       // EMA Period
input int    InpMACDFast     = 12;        // MACD Fast
input int    InpMACDSlow     = 26;        // MACD Slow
input int    InpMACDSignal   = 9;         // MACD Signal
input int    InpRSIPeriod    = 14;        // RSI Period
input int    InpStochK       = 14;        // Stochastic %K
input int    InpStochD       = 3;         // Stochastic %D
input int    InpStochSlowing = 3;         // Stochastic Slowing
input int    InpATRPeriod    = 14;        // ATR Period

//--- Global Variables
CTrade      trade;
CSymbolInfo symbol;
datetime    lastBarTime = 0;
int         minBarsRequired;
bool        indicatorsReady = false;
int         initializationAttempts = 0;

//--- Indicator Handles
int ema_handle = INVALID_HANDLE;
int macd_handle = INVALID_HANDLE;
int rsi_handle = INVALID_HANDLE;
int stoch_handle = INVALID_HANDLE;
int atr_handle = INVALID_HANDLE;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
    symbol.Name(_Symbol);
    trade.SetExpertMagicNumber(67890);
    trade.SetMarginMode();
    
    initializationAttempts++;
    PrintFormat("CNN-LSTM EA initialization attempt %d", initializationAttempts);

    //--- Calculate minimum bars required
    int macd_total_period = InpMACDSlow + InpMACDSignal;
    int max_indicator_period = MathMax(InpMAPeriod, MathMax(macd_total_period, MathMax(InpRSIPeriod, MathMax(InpStochK, InpATRPeriod))));
    minBarsRequired = InpLookBack + max_indicator_period + 10; // Extra buffer for safety

    //--- Check for enough bars on chart
    int available_bars = Bars(_Symbol, _Period);
    if(available_bars < minBarsRequired)
    {
        PrintFormat("Not enough history on the chart. Required: %d, Available: %d", minBarsRequired, available_bars);
        PrintFormat("Please load more historical data or reduce the look-back period.");
        return(INIT_FAILED);
    }

    //--- Initialize all indicators with error checking
    if(!InitializeIndicators())
    {
        Print("Failed to initialize indicators. Please check symbol and timeframe.");
        return(INIT_FAILED);
    }

    //--- Wait for indicators to calculate initial values
    if(!WaitForIndicatorCalculation())
    {
        Print("Indicators failed to calculate initial values. Retrying...");
        if(initializationAttempts < 3)
        {
            Sleep(1000);
            return(INIT_FAILED); // This will trigger re-initialization
        }
        else
        {
            Print("Maximum initialization attempts reached. Please restart EA.");
            return(INIT_FAILED);
        }
    }

    indicatorsReady = true;
    PrintFormat("CNN-LSTM EA initialized successfully. Minimum bars required: %d", minBarsRequired);
    Comment("CNN-LSTM EA: Ready for trading");
    return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Initialize all indicators with comprehensive error checking      |
//+------------------------------------------------------------------+
bool InitializeIndicators()
{
    // Release any existing handles first
    ReleaseIndicators();
    
    PrintFormat("Initializing indicators for %s %s", _Symbol, EnumToString(_Period));
    
    //--- Initialize EMA
    ema_handle = iMA(_Symbol, _Period, InpMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
    if(ema_handle == INVALID_HANDLE)
    {
        PrintFormat("Failed to create EMA indicator handle. Error: %d", GetLastError());
        return false;
    }
    
    //--- Initialize MACD
    macd_handle = iMACD(_Symbol, _Period, InpMACDFast, InpMACDSlow, InpMACDSignal, PRICE_CLOSE);
    if(macd_handle == INVALID_HANDLE)
    {
        PrintFormat("Failed to create MACD indicator handle. Error: %d", GetLastError());
        return false;
    }
    
    //--- Initialize RSI
    rsi_handle = iRSI(_Symbol, _Period, InpRSIPeriod, PRICE_CLOSE);
    if(rsi_handle == INVALID_HANDLE)
    {
        PrintFormat("Failed to create RSI indicator handle. Error: %d", GetLastError());
        return false;
    }
    
    //--- Initialize Stochastic
    stoch_handle = iStochastic(_Symbol, _Period, InpStochK, InpStochD, InpStochSlowing, MODE_SMA, STO_LOWHIGH);
    if(stoch_handle == INVALID_HANDLE)
    {
        PrintFormat("Failed to create Stochastic indicator handle. Error: %d", GetLastError());
        return false;
    }
    
    //--- Initialize ATR
    atr_handle = iATR(_Symbol, _Period, InpATRPeriod);
    if(atr_handle == INVALID_HANDLE)
    {
        PrintFormat("Failed to create ATR indicator handle. Error: %d", GetLastError());
        return false;
    }
    
    Print("All indicator handles created successfully");
    return true;
}

//+------------------------------------------------------------------+
//| Wait for indicator calculation to complete                       |
//+------------------------------------------------------------------+
bool WaitForIndicatorCalculation()
{
    Print("Waiting for indicator calculations to complete...");
    
    int max_wait_seconds = 30;
    int wait_count = 0;
    
    while(wait_count < max_wait_seconds)
    {
        // Check if we have calculated values for each indicator
        if(BarsCalculated(ema_handle) >= minBarsRequired &&
           BarsCalculated(macd_handle) >= minBarsRequired &&
           BarsCalculated(rsi_handle) >= minBarsRequired &&
           BarsCalculated(stoch_handle) >= minBarsRequired &&
           BarsCalculated(atr_handle) >= minBarsRequired)
        {
            PrintFormat("All indicators ready after %d seconds", wait_count);
            return true;
        }
        
        Sleep(1000);
        wait_count++;
        
        if(wait_count % 5 == 0)
        {
            PrintFormat("Still waiting for indicators... (%d/%d seconds)", wait_count, max_wait_seconds);
            PrintFormat("EMA: %d, MACD: %d, RSI: %d, Stoch: %d, ATR: %d bars calculated", 
                       BarsCalculated(ema_handle), BarsCalculated(macd_handle), 
                       BarsCalculated(rsi_handle), BarsCalculated(stoch_handle), 
                       BarsCalculated(atr_handle));
        }
    }
    
    Print("Timeout waiting for indicator calculations");
    return false;
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
    ReleaseIndicators();
    Comment("");
    PrintFormat("CNN-LSTM EA deinitialized. Reason: %d", reason);
}

//+------------------------------------------------------------------+
//| Release all indicator handles                                    |
//+------------------------------------------------------------------+
void ReleaseIndicators()
{
    if(ema_handle != INVALID_HANDLE) IndicatorRelease(ema_handle);
    if(macd_handle != INVALID_HANDLE) IndicatorRelease(macd_handle);
    if(rsi_handle != INVALID_HANDLE) IndicatorRelease(rsi_handle);
    if(stoch_handle != INVALID_HANDLE) IndicatorRelease(stoch_handle);
    if(atr_handle != INVALID_HANDLE) IndicatorRelease(atr_handle);
    
    ema_handle = INVALID_HANDLE;
    macd_handle = INVALID_HANDLE;
    rsi_handle = INVALID_HANDLE;
    stoch_handle = INVALID_HANDLE;
    atr_handle = INVALID_HANDLE;
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
    if(!indicatorsReady)
    {
        Comment("CNN-LSTM EA: Indicators not ready");
        return;
    }
    
    if(IsNewBar())
    {
        CheckForSignal();
    }
}

//+------------------------------------------------------------------+
//| Check for a trading signal from the API                          |
//+------------------------------------------------------------------+
void CheckForSignal()
{
    if(PositionsTotal() > 0) 
    {
        Comment("CNN-LSTM EA: Position already open");
        return; // Only trade if no open positions
    }

    //--- Ensure we have enough bars
    if(Bars(_Symbol, _Period) < minBarsRequired)
    {
        Comment("CNN-LSTM EA: Not enough bars for analysis");
        return;
    }

    int signal = GetPrediction();
    
    if(signal == 0) 
    {
        Comment("CNN-LSTM EA: No signal or API error");
        return; // No signal or error
    }

    // Get ATR for position sizing
    double atr_val[];
    if(!GetIndicatorValue(atr_handle, 0, 1, atr_val))
    {
        Comment("CNN-LSTM EA: Failed to get ATR value");
        return;
    }
    
    double lot_size = CalculateLotSize(atr_val[0]);
    double sl = 0, tp = 0;

    if(signal == 1) // Buy Signal
    {
        sl = symbol.Ask() - atr_val[0] * InpSLMultiplier;
        tp = symbol.Ask() + atr_val[0] * InpTPMultiplier;
        
        if(trade.Buy(lot_size, _Symbol, symbol.Ask(), sl, tp, "CNN-LSTM Buy"))
        {
            PrintFormat("Buy order placed: Lot=%.2f, SL=%.5f, TP=%.5f", lot_size, sl, tp);
            Comment("CNN-LSTM EA: Buy order placed");
        }
        else
        {
            PrintFormat("Failed to place buy order. Error: %d", GetLastError());
        }
    }
    else if(signal == -1) // Sell Signal
    {
        sl = symbol.Bid() + atr_val[0] * InpSLMultiplier;
        tp = symbol.Bid() - atr_val[0] * InpTPMultiplier;
        
        if(trade.Sell(lot_size, _Symbol, symbol.Bid(), sl, tp, "CNN-LSTM Sell"))
        {
            PrintFormat("Sell order placed: Lot=%.2f, SL=%.5f, TP=%.5f", lot_size, sl, tp);
            Comment("CNN-LSTM EA: Sell order placed");
        }
        else
        {
            PrintFormat("Failed to place sell order. Error: %d", GetLastError());
        }
    }
}

//+------------------------------------------------------------------+
//| Robust indicator value retrieval with retry logic               |
//+------------------------------------------------------------------+
bool GetIndicatorValue(int handle, int buffer, int count, double &values[])
{
    for(int attempt = 0; attempt < InpMaxRetries; attempt++)
    {
        ResetLastError();
        
        if(CopyBuffer(handle, buffer, 0, count, values) == count)
        {
            return true;
        }
        
        int error = GetLastError();
        if(attempt < InpMaxRetries - 1)
        {
            PrintFormat("Attempt %d failed to copy buffer. Error: %d. Retrying in %dms...", 
                       attempt + 1, error, InpRetryDelay);
            Sleep(InpRetryDelay);
        }
        else
        {
            PrintFormat("All %d attempts failed to copy buffer. Final error: %d", InpMaxRetries, error);
        }
    }
    
    return false;
}

//+------------------------------------------------------------------+
//| Get prediction from Python API server                            |
//+------------------------------------------------------------------+
int GetPrediction()
{
    string json_payload = BuildJsonPayload();
    if(json_payload == "") 
    {
        Print("Failed to build JSON payload");
        return 0;
    }

    char post_data[], result_data[];
    string headers = "Content-Type: application/json\r\n";
    int timeout = 10000; // 10 seconds

    StringToCharArray(json_payload, post_data);

    ResetLastError();
    int res = WebRequest("POST", InpApiEndpoint, NULL, timeout, post_data, result_data, headers);

    if(res == -1)
    {
        int error = GetLastError();
        PrintFormat("WebRequest failed. Error code: %d", error);
        
        if(error == 4014)
        {
            Print("WebRequest not allowed. Please add the URL to the list of allowed URLs in Tools->Options->Expert Advisors");
        }
        
        return 0;
    }

    string result_str = CharArrayToString(result_data);
    
    //--- Simple JSON parsing to find the signal value
    int signal_pos = StringFind(result_str, "\"signal\":");
    if(signal_pos < 0)
    {
        PrintFormat("Could not find 'signal' in API response: %s", result_str);
        return 0;
    }
    
    string signal_substr = StringSubstr(result_str, signal_pos + 9); // 9 is len of "signal":
    int comma_pos = StringFind(signal_substr, ",");
    int brace_pos = StringFind(signal_substr, "}");
    int end_pos = (comma_pos > 0 && comma_pos < brace_pos) ? comma_pos : brace_pos;
    
    if(end_pos <= 0) end_pos = StringLen(signal_substr);
    
    string signal_value = StringSubstr(signal_substr, 0, end_pos);
    int signal = (int)StringToInteger(signal_value);

    PrintFormat("Received signal from API: %d", signal);
    return signal;
}

//+------------------------------------------------------------------+
//| Build the JSON payload with feature data - ROBUST VERSION       |
//+------------------------------------------------------------------+
string BuildJsonPayload()
{
    string payload = "{\"features\": [";
    
    // Calculate required data points
    int data_to_copy = InpLookBack + 10; // Extra buffer for safety
    
    // Declare all arrays
    double ema[], macd_main[], macd_hist[], macd_sig[], rsi[], stoch_k[], stoch_d[], atr_val[];
    MqlRates rates[];

    // Robust data copying with comprehensive error handling
    bool all_data_copied = false;
    
    for(int attempt = 0; attempt < InpMaxRetries; attempt++)
    {
        ResetLastError();
        
        PrintFormat("Data copy attempt %d/%d", attempt + 1, InpMaxRetries);
        
        // Step 1: Copy rates data first
        if(CopyRates(_Symbol, _Period, 0, data_to_copy, rates) < data_to_copy)
        {
            PrintFormat("Failed to copy rates data. Error: %d", GetLastError());
            if(attempt < InpMaxRetries - 1) Sleep(InpRetryDelay);
            continue;
        }
        
        // Step 2: Copy all indicator buffers
        bool indicators_copied = true;
        
        if(!GetIndicatorValue(ema_handle, 0, data_to_copy, ema))
        {
            Print("Failed to copy EMA data");
            indicators_copied = false;
        }
        
        if(!GetIndicatorValue(macd_handle, 0, data_to_copy, macd_main))
        {
            Print("Failed to copy MACD main line data");
            indicators_copied = false;
        }
        
        if(!GetIndicatorValue(macd_handle, 2, data_to_copy, macd_hist))
        {
            Print("Failed to copy MACD histogram data");
            indicators_copied = false;
        }
        
        if(!GetIndicatorValue(macd_handle, 1, data_to_copy, macd_sig))
        {
            Print("Failed to copy MACD signal data");
            indicators_copied = false;
        }
        
        if(!GetIndicatorValue(rsi_handle, 0, data_to_copy, rsi))
        {
            Print("Failed to copy RSI data");
            indicators_copied = false;
        }
        
        if(!GetIndicatorValue(stoch_handle, 0, data_to_copy, stoch_k))
        {
            Print("Failed to copy Stochastic %K data");
            indicators_copied = false;
        }
        
        if(!GetIndicatorValue(stoch_handle, 1, data_to_copy, stoch_d))
        {
            Print("Failed to copy Stochastic %D data");
            indicators_copied = false;
        }
        
        if(!GetIndicatorValue(atr_handle, 0, data_to_copy, atr_val))
        {
            Print("Failed to copy ATR data");
            indicators_copied = false;
        }
        
        if(indicators_copied)
        {
            all_data_copied = true;
            PrintFormat("Successfully copied all data on attempt %d", attempt + 1);
            break;
        }
        else
        {
            PrintFormat("Attempt %d failed. Retrying in %dms...", attempt + 1, InpRetryDelay);
            if(attempt < InpMaxRetries - 1) Sleep(InpRetryDelay);
        }
    }

    if(!all_data_copied)
    {
        Print("Failed to copy all required data after maximum attempts");
        return "";
    }

    // Build the feature array
    for(int i = InpLookBack - 1; i >= 0; i--)
    {
        // Validate data before using
        if(i >= ArraySize(rates) || i >= ArraySize(ema) || i >= ArraySize(macd_main) || 
           i >= ArraySize(rsi) || i >= ArraySize(stoch_k) || i >= ArraySize(atr_val))
        {
            PrintFormat("Data array size mismatch at index %d", i);
            return "";
        }
        
        // Calculate ATR percentage
        double atr_perc = (rates[i].close > 0) ? (atr_val[i] / rates[i].close) * 100 : 0;
        
        // Validate all values are not NaN or infinite
        if(!IsValidValue(ema[i]) || !IsValidValue(macd_main[i]) || !IsValidValue(macd_hist[i]) ||
           !IsValidValue(macd_sig[i]) || !IsValidValue(rsi[i]) || !IsValidValue(stoch_k[i]) ||
           !IsValidValue(stoch_d[i]) || !IsValidValue(atr_perc))
        {
            PrintFormat("Invalid data detected at index %d", i);
            return "";
        }
        
        string feature_set = StringFormat(
            "{ \"EMA_%d\":%.5f, \"MACD_%d_%d_%d\":%.5f, \"MACDh_%d_%d_%d\":%.5f, \"MACDs_%d_%d_%d\":%.5f, \"RSI_%d\":%.5f, \"STOCHk_%d_%d_%d\":%.5f, \"STOCHd_%d_%d_%d\":%.5f, \"ATRr_%d\":%.5f }",
            InpMAPeriod, ema[i],
            InpMACDFast, InpMACDSlow, InpMACDSignal, macd_main[i],
            InpMACDFast, InpMACDSlow, InpMACDSignal, macd_hist[i],
            InpMACDFast, InpMACDSlow, InpMACDSignal, macd_sig[i],
            InpRSIPeriod, rsi[i],
            InpStochK, InpStochD, InpStochSlowing, stoch_k[i],
            InpStochK, InpStochD, InpStochSlowing, stoch_d[i],
            InpATRPeriod, atr_perc
        );
        
        payload += feature_set;
        if(i > 0) payload += ",";
    }

    payload += "]}";
    
    // Validate final JSON length
    if(StringLen(payload) > 1000000) // 1MB limit
    {
        Print("JSON payload too large. Reducing data...");
        return "";
    }
    
    return payload;
}

//+------------------------------------------------------------------+
//| Validate if a value is finite and not NaN                       |
//+------------------------------------------------------------------+
bool IsValidValue(double value)
{
    return !MathIsValidNumber(value) ? false : true;
}

//+------------------------------------------------------------------+
//| Calculate Lot Size based on risk                                 |
//+------------------------------------------------------------------+
double CalculateLotSize(double atr_value)
{
    double account_balance = AccountInfoDouble(ACCOUNT_BALANCE);
    double risk_amount = account_balance * InpRiskPerTrade;
    double sl_pips = atr_value * InpSLMultiplier;
    
    if(sl_pips <= 0 || risk_amount <= 0) return symbol.LotsMin();

    double tick_value = symbol.TickValue();
    if(tick_value <= 0) return symbol.LotsMin();
    
    double lot_size = risk_amount / (sl_pips * tick_value);
    
    // Normalize and validate lot size
    lot_size = NormalizeDouble(lot_size, 2);
    lot_size = MathMax(symbol.LotsMin(), lot_size);
    lot_size = MathMin(symbol.LotsMax(), lot_size);
    
    return lot_size;
}

//+------------------------------------------------------------------+
//| Check for a new bar                                              |
//+------------------------------------------------------------------+
bool IsNewBar()
{
    datetime current_time = iTime(_Symbol, _Period, 0);
    if(lastBarTime != current_time)
    {
        lastBarTime = current_time;
        return true;
    }
    return false;
}

//+------------------------------------------------------------------+