
//+------------------------------------------------------------------+
//|                  triple_threat_Optimized.mq5                     |
//|      Generated by ML Backtester Framework - Copyright 2025       |
//+------------------------------------------------------------------+
#property copyright "Copyright 2025, ML Backtester Framework"
#property link      "https://github.com/your_repo"
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>
#include <Trade\SymbolInfo.mqh>

//--- Optimized Input Parameters
input double InpRiskPerTrade = 0.01;      // Risk per trade as a percentage of account balance
input double InpSLMultiplier = 2.417992110316982;    // Stop Loss ATR Multiplier
input double InpTPMultiplier = 4.79637847609745;    // Take Profit ATR Multiplier
input int    InpMAPeriod     = 200;      // EMA Period for Trend
input int    InpMACDFast     = 12;       // MACD Fast EMA
input int    InpMACDSlow     = 26;       // MACD Slow EMA
input int    InpMACDSignal   = 9;        // MACD Signal Line
input int    InpStochK       = 14;       // Stochastic %K
input int    InpStochD       = 3;        // Stochastic %D
input int    InpStochSlowing = 3;        // Stochastic Slowing
input int    InpATRPeriod    = 14;       // ATR Period for SL/TP

//--- Global Variables
CTrade      trade;
CSymbolInfo symbol;
datetime    lastBarTime = 0;

//--- Indicator Handles
int ema_handle;
int macd_handle;
int stoch_handle;
int atr_handle;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   symbol.Name(_Symbol);
   trade.SetExpertMagicNumber(12345);
   trade.SetMarginMode();

   ema_handle = iMA(_Symbol, _Period, InpMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   macd_handle = iMACD(_Symbol, _Period, InpMACDFast, InpMACDSlow, InpMACDSignal, PRICE_CLOSE);
   stoch_handle = iStochastic(_Symbol, _Period, InpStochK, InpStochD, InpStochSlowing, MODE_SMA, STO_LOWHIGH);
   atr_handle = iATR(_Symbol, _Period, InpATRPeriod);

   if(ema_handle < 0 || macd_handle < 0 || stoch_handle < 0 || atr_handle < 0)
     {
      printf("Error initializing indicators");
      return(INIT_FAILED);
     }

   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   IndicatorRelease(ema_handle);
   IndicatorRelease(macd_handle);
   IndicatorRelease(stoch_handle);
   IndicatorRelease(atr_handle);
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(IsNewBar())
     {
      CheckForSignal();
     }
  }

//+------------------------------------------------------------------+
//| Check for trading signals                                        |
//+------------------------------------------------------------------+
void CheckForSignal()
  {
   // --- Get Indicator Values ---
   double ema[], macd_main[], macd_signal[], stoch_main[], stoch_signal[], atr[];
   if(CopyBuffer(ema_handle, 0, 1, 1, ema) <= 0 ||
      CopyBuffer(macd_handle, 0, 1, 2, macd_main) <= 0 ||
      CopyBuffer(macd_handle, 1, 1, 2, macd_signal) <= 0 ||
      CopyBuffer(stoch_handle, 0, 1, 2, stoch_main) <= 0 ||
      CopyBuffer(stoch_handle, 1, 1, 2, stoch_signal) <= 0 ||
      CopyBuffer(atr_handle, 0, 1, 1, atr) <= 0)
     {
      printf("Error copying indicator buffers");
      return;
     }

   MqlRates rates[2];
   if(CopyRates(_Symbol, _Period, 1, 2, rates) < 2) return;
   double current_close = rates[1].close;
   double prev_stoch_main = stoch_main[1];

   // --- Trading Conditions ---
   bool long_trend = current_close > ema[0];
   bool long_momentum = macd_main[0] > macd_signal[0];
   bool long_entry = stoch_main[0] > prev_stoch_main && prev_stoch_main < 20;

   bool short_trend = current_close < ema[0];
   bool short_momentum = macd_main[0] < macd_signal[0];
   bool short_entry = stoch_main[0] < prev_stoch_main && prev_stoch_main > 80;

   // --- Execution ---
   if(PositionsTotal() == 0)
     {
      double lot_size = CalculateLotSize(atr[0]);
      double sl = 0, tp = 0;

      if(long_trend && long_momentum && long_entry)
        {
         sl = symbol.Ask() - atr[0] * InpSLMultiplier;
         tp = symbol.Ask() + atr[0] * InpTPMultiplier;
         trade.Buy(lot_size, _Symbol, symbol.Ask(), sl, tp, "Buy Signal");
        }
      else if(short_trend && short_momentum && short_entry)
        {
         sl = symbol.Bid() + atr[0] * InpSLMultiplier;
         tp = symbol.Bid() - atr[0] * InpTPMultiplier;
         trade.Sell(lot_size, _Symbol, symbol.Bid(), sl, tp, "Sell Signal");
        }
     }
  }

//+------------------------------------------------------------------+
//| Calculate Lot Size based on risk                                 |
//+------------------------------------------------------------------+
double CalculateLotSize(double atr_value)
  {
   double account_balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double risk_amount = account_balance * InpRiskPerTrade;
   double sl_pips = atr_value * InpSLMultiplier;
   
   if(sl_pips == 0) return 0.01;

   double tick_value = symbol.TickValue();
   double lot_size = risk_amount / (sl_pips * tick_value);

   lot_size = NormalizeDouble(lot_size, 2);
   if(lot_size < symbol.LotsMin()) lot_size = symbol.LotsMin();
   if(lot_size > symbol.LotsMax()) lot_size = symbol.LotsMax();
   
   return lot_size;
  }

//+------------------------------------------------------------------+
//| Check for a new bar                                              |
//+------------------------------------------------------------------+
bool IsNewBar()
  {
   datetime server_time = TimeCurrent();
   if(lastBarTime != iTime(_Symbol, _Period, 0))
     {
      lastBarTime = iTime(_Symbol, _Period, 0);
      return(true);
     }
   return(false);
  }
//+------------------------------------------------------------------+
