//+------------------------------------------------------------------+
//|         test_cnn_lstm_ea_fixed.mq5 - API Client (FIXED)         |
//|      Generated by ML Backtester Framework - Copyright 2025       |
//|      Fixed Error 4806 - Buffer copying and StringFormat issues  |
//+------------------------------------------------------------------+
#property copyright "Copyright 2025, ML Backtester Framework"
#property link      "https://github.com/your_repo"
#property version   "1.01"
#property strict

#include <Trade\Trade.mqh>
#include <Trade\SymbolInfo.mqh>

//--- EA Inputs
input string InpApiEndpoint = "http://192.168.0.244:5001/predict"; // API Endpoint for predictions
input double InpRiskPerTrade = 0.01;      // Risk per trade
input double InpSLMultiplier = 2.5;       // Stop Loss ATR Multiplier
input double InpTPMultiplier = 3.5;       // Take Profit ATR Multiplier
input int    InpLookBack     = 96;        // Model Look-back period
input int    InpMaxRetries   = 10;        // Maximum retry attempts for data copying
input int    InpRetryDelay   = 200;       // Delay between retries (ms)

//--- Indicator Parameters (must match training)
input int    InpMAPeriod     = 200;
input int    InpMACDFast     = 12;
input int    InpMACDSlow     = 26;
input int    InpMACDSignal   = 9;
input int    InpRSIPeriod    = 14;
input int    InpStochK       = 14;
input int    InpStochD       = 3;
input int    InpStochSlowing = 3;
input int    InpATRPeriod    = 14;

//--- Global Variables
CTrade      trade;
CSymbolInfo symbol;
datetime    lastBarTime = 0;
int         minBarsRequired;
bool        indicatorsReady = false;

//--- Indicator Handles
int ema_handle = INVALID_HANDLE;
int macd_handle = INVALID_HANDLE;
int rsi_handle = INVALID_HANDLE;
int stoch_handle = INVALID_HANDLE;
int atr_handle = INVALID_HANDLE;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
    symbol.Name(_Symbol);
    trade.SetExpertMagicNumber(67890);
    trade.SetMarginMode();

    PrintFormat("CNN-LSTM EA: Starting initialization for %s %s", _Symbol, EnumToString(_Period));

    //--- Calculate minimum bars required
    int macd_total_period = InpMACDSlow + InpMACDSignal;
    int max_indicator_period = MathMax(InpMAPeriod, MathMax(macd_total_period, MathMax(InpRSIPeriod, MathMax(InpStochK, InpATRPeriod))));
    minBarsRequired = InpLookBack + max_indicator_period + 50; // Extra buffer for safety

    //--- Check for enough bars on chart
    int available_bars = Bars(_Symbol, _Period);
    if(available_bars < minBarsRequired)
    {
        PrintFormat("Not enough history on the chart. Required: %d, Available: %d", minBarsRequired, available_bars);
        PrintFormat("Please load more historical data or reduce the look-back period.");
        return(INIT_FAILED);
    }

    //--- Initialize all indicators with proper error checking
    if(!InitializeIndicators())
    {
        Print("Failed to initialize indicators.");
        return(INIT_FAILED);
    }

    //--- Wait for indicators to be ready
    if(!WaitForIndicatorData())
    {
        Print("Indicators failed to calculate sufficient data.");
        return(INIT_FAILED);
    }

    indicatorsReady = true;
    PrintFormat("CNN-LSTM EA initialized successfully. Minimum bars: %d, Available: %d", minBarsRequired, available_bars);
    Comment("CNN-LSTM EA: Ready for trading");
    return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Initialize all indicators with error checking                    |
//+------------------------------------------------------------------+
bool InitializeIndicators()
{
    // Release any existing handles
    ReleaseIndicators();
    
    //--- Initialize EMA
    ema_handle = iMA(_Symbol, _Period, InpMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
    if(ema_handle == INVALID_HANDLE)
    {
        PrintFormat("Failed to create EMA indicator. Error: %d", GetLastError());
        return false;
    }
    
    //--- Initialize MACD
    macd_handle = iMACD(_Symbol, _Period, InpMACDFast, InpMACDSlow, InpMACDSignal, PRICE_CLOSE);
    if(macd_handle == INVALID_HANDLE)
    {
        PrintFormat("Failed to create MACD indicator. Error: %d", GetLastError());
        return false;
    }
    
    //--- Initialize RSI
    rsi_handle = iRSI(_Symbol, _Period, InpRSIPeriod, PRICE_CLOSE);
    if(rsi_handle == INVALID_HANDLE)
    {
        PrintFormat("Failed to create RSI indicator. Error: %d", GetLastError());
        return false;
    }
    
    //--- Initialize Stochastic
    stoch_handle = iStochastic(_Symbol, _Period, InpStochK, InpStochD, InpStochSlowing, MODE_SMA, STO_LOWHIGH);
    if(stoch_handle == INVALID_HANDLE)
    {
        PrintFormat("Failed to create Stochastic indicator. Error: %d", GetLastError());
        return false;
    }
    
    //--- Initialize ATR
    atr_handle = iATR(_Symbol, _Period, InpATRPeriod);
    if(atr_handle == INVALID_HANDLE)
    {
        PrintFormat("Failed to create ATR indicator. Error: %d", GetLastError());
        return false;
    }
    
    Print("All indicator handles created successfully");
    return true;
}

//+------------------------------------------------------------------+
//| Wait for indicators to calculate sufficient data                 |
//+------------------------------------------------------------------+
bool WaitForIndicatorData()
{
    Print("Waiting for indicator calculations...");
    
    int max_wait_seconds = 30;
    int wait_count = 0;
    
    while(wait_count < max_wait_seconds)
    {
        if(BarsCalculated(ema_handle) >= minBarsRequired &&
           BarsCalculated(macd_handle) >= minBarsRequired &&
           BarsCalculated(rsi_handle) >= minBarsRequired &&
           BarsCalculated(stoch_handle) >= minBarsRequired &&
           BarsCalculated(atr_handle) >= minBarsRequired)
        {
            PrintFormat("All indicators ready after %d seconds", wait_count);
            return true;
        }
        
        Sleep(1000);
        wait_count++;
        
        if(wait_count % 5 == 0)
        {
            PrintFormat("Waiting... EMA:%d MACD:%d RSI:%d Stoch:%d ATR:%d (need %d)", 
                       BarsCalculated(ema_handle), BarsCalculated(macd_handle), 
                       BarsCalculated(rsi_handle), BarsCalculated(stoch_handle), 
                       BarsCalculated(atr_handle), minBarsRequired);
        }
    }
    
    Print("Timeout waiting for indicator calculations");
    return false;
}

//+------------------------------------------------------------------+
//| Release all indicator handles                                    |
//+------------------------------------------------------------------+
void ReleaseIndicators()
{
    if(ema_handle != INVALID_HANDLE) IndicatorRelease(ema_handle);
    if(macd_handle != INVALID_HANDLE) IndicatorRelease(macd_handle);
    if(rsi_handle != INVALID_HANDLE) IndicatorRelease(rsi_handle);
    if(stoch_handle != INVALID_HANDLE) IndicatorRelease(stoch_handle);
    if(atr_handle != INVALID_HANDLE) IndicatorRelease(atr_handle);
    
    ema_handle = INVALID_HANDLE;
    macd_handle = INVALID_HANDLE;
    rsi_handle = INVALID_HANDLE;
    stoch_handle = INVALID_HANDLE;
    atr_handle = INVALID_HANDLE;
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
    ReleaseIndicators();
    Comment("");
    PrintFormat("CNN-LSTM EA deinitialized. Reason: %d", reason);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
    if(!indicatorsReady)
    {
        Comment("CNN-LSTM EA: Indicators not ready");
        return;
    }
    
    if(IsNewBar())
    {
        CheckForSignal();
    }
}

//+------------------------------------------------------------------+
//| Check for a trading signal from the API                          |
//+------------------------------------------------------------------+
void CheckForSignal()
{
    if(PositionsTotal() > 0) 
    {
        Comment("CNN-LSTM EA: Position already open");
        return;
    }

    //--- Ensure we have enough bars
    if(Bars(_Symbol, _Period) < minBarsRequired)
    {
        Comment("CNN-LSTM EA: Not enough bars");
        return;
    }

    int signal = GetPrediction();

    if(signal == 0) 
    {
        Comment("CNN-LSTM EA: No signal or API error");
        return;
    }

    double atr_val[];
    if(!SafeCopyBuffer(atr_handle, 0, 0, 1, atr_val))
    {
        Comment("CNN-LSTM EA: Failed to get ATR value");
        return;
    }
    
    double lot_size = CalculateLotSize(atr_val[0]);
    double sl = 0, tp = 0;

    if(signal == 1) // Buy Signal
    {
        sl = symbol.Ask() - atr_val[0] * InpSLMultiplier;
        tp = symbol.Ask() + atr_val[0] * InpTPMultiplier;
        
        if(trade.Buy(lot_size, _Symbol, symbol.Ask(), sl, tp, "CNN-LSTM Buy"))
        {
            PrintFormat("Buy order placed: Lot=%.2f, SL=%.5f, TP=%.5f", lot_size, sl, tp);
            Comment("CNN-LSTM EA: Buy order placed");
        }
    }
    else if(signal == -1) // Sell Signal
    {
        sl = symbol.Bid() + atr_val[0] * InpSLMultiplier;
        tp = symbol.Bid() - atr_val[0] * InpTPMultiplier;
        
        if(trade.Sell(lot_size, _Symbol, symbol.Bid(), sl, tp, "CNN-LSTM Sell"))
        {
            PrintFormat("Sell order placed: Lot=%.2f, SL=%.5f, TP=%.5f", lot_size, sl, tp);
            Comment("CNN-LSTM EA: Sell order placed");
        }
    }
}

//+------------------------------------------------------------------+
//| Safe buffer copying with retry logic                             |
//+------------------------------------------------------------------+
bool SafeCopyBuffer(int handle, int buffer_num, int start_pos, int count, double &buffer[])
{
    for(int attempt = 0; attempt < InpMaxRetries; attempt++)
    {
        ResetLastError();
        
        if(CopyBuffer(handle, buffer_num, start_pos, count, buffer) == count)
        {
            return true;
        }
        
        int error = GetLastError();
        if(attempt < InpMaxRetries - 1)
        {
            PrintFormat("Buffer copy attempt %d failed. Error: %d. Retrying in %dms...", 
                       attempt + 1, error, InpRetryDelay);
            Sleep(InpRetryDelay);
        }
        else
        {
            PrintFormat("All %d buffer copy attempts failed. Final error: %d", InpMaxRetries, error);
        }
    }
    
    return false;
}

//+------------------------------------------------------------------+
//| Get prediction from Python API server                            |
//+------------------------------------------------------------------+
int GetPrediction()
{
    string json_payload = BuildJsonPayload();
    if(json_payload == "") 
    {
        Print("Failed to build JSON payload");
        return 0;
    }

    char post_data[], result_data[];
    string headers = "Content-Type: application/json\r\n";
    int timeout = 10000; // 10 seconds

    StringToCharArray(json_payload, post_data);

    ResetLastError();
    int res = WebRequest("POST", InpApiEndpoint, NULL, timeout, post_data, result_data, headers);

    if(res == -1)
    {
        int error = GetLastError();
        PrintFormat("WebRequest failed. Error: %d", error);
        
        if(error == 4014)
        {
            Print("WebRequest not allowed. Add URL to allowed list in Tools->Options->Expert Advisors");
        }
        
        return 0;
    }

    string result_str = CharArrayToString(result_data);
    
    //--- Parse JSON response for signal
    int signal_pos = StringFind(result_str, "\"signal\":");
    if(signal_pos < 0)
    {
        PrintFormat("Signal not found in API response: %s", result_str);
        return 0;
    }
    
    string signal_substr = StringSubstr(result_str, signal_pos + 9);
    int comma_pos = StringFind(signal_substr, ",");
    int brace_pos = StringFind(signal_substr, "}");
    int end_pos = (comma_pos > 0 && comma_pos < brace_pos) ? comma_pos : brace_pos;
    
    if(end_pos <= 0) end_pos = StringLen(signal_substr);
    
    string signal_value = StringSubstr(signal_substr, 0, end_pos);
    int signal = (int)StringToInteger(signal_value);

    PrintFormat("API signal: %d", signal);
    return signal;
}

//+------------------------------------------------------------------+
//| Build JSON payload - FIXED VERSION                               |
//+------------------------------------------------------------------+
string BuildJsonPayload()
{
    string payload = "{\"features\": [";
    
    // Calculate data requirements
    int data_to_copy = InpLookBack + 10; // Safety buffer
    
    // Declare arrays
    double ema[], macd_main[], macd_hist[], macd_sig[], rsi[], stoch_k[], stoch_d[], atr_val[];
    MqlRates rates[];

    // Copy all data with comprehensive error handling
    bool all_data_ready = false;
    
    for(int attempt = 0; attempt < InpMaxRetries; attempt++)
    {
        PrintFormat("Data collection attempt %d/%d", attempt + 1, InpMaxRetries);
        
        // Copy rates first
        if(CopyRates(_Symbol, _Period, 0, data_to_copy, rates) < data_to_copy)
        {
            PrintFormat("Failed to copy rates. Error: %d", GetLastError());
            if(attempt < InpMaxRetries - 1) Sleep(InpRetryDelay);
            continue;
        }
        
        // Copy all indicator buffers
        bool indicators_ok = true;
        
        if(!SafeCopyBuffer(ema_handle, 0, 0, data_to_copy, ema))
        {
            Print("Failed to copy EMA data");
            indicators_ok = false;
        }
        
        if(!SafeCopyBuffer(macd_handle, 0, 0, data_to_copy, macd_main))
        {
            Print("Failed to copy MACD main line");
            indicators_ok = false;
        }
        
        if(!SafeCopyBuffer(macd_handle, 2, 0, data_to_copy, macd_hist))
        {
            Print("Failed to copy MACD histogram");
            indicators_ok = false;
        }
        
        if(!SafeCopyBuffer(macd_handle, 1, 0, data_to_copy, macd_sig))
        {
            Print("Failed to copy MACD signal");
            indicators_ok = false;
        }
        
        if(!SafeCopyBuffer(rsi_handle, 0, 0, data_to_copy, rsi))
        {
            Print("Failed to copy RSI data");
            indicators_ok = false;
        }
        
        if(!SafeCopyBuffer(stoch_handle, 0, 0, data_to_copy, stoch_k))
        {
            Print("Failed to copy Stochastic %K");
            indicators_ok = false;
        }
        
        if(!SafeCopyBuffer(stoch_handle, 1, 0, data_to_copy, stoch_d))
        {
            Print("Failed to copy Stochastic %D");
            indicators_ok = false;
        }
        
        if(!SafeCopyBuffer(atr_handle, 0, 0, data_to_copy, atr_val))
        {
            Print("Failed to copy ATR data");
            indicators_ok = false;
        }
        
        if(indicators_ok)
        {
            all_data_ready = true;
            PrintFormat("All data copied successfully on attempt %d", attempt + 1);
            break;
        }
        else if(attempt < InpMaxRetries - 1)
        {
            PrintFormat("Attempt %d failed, retrying in %dms...", attempt + 1, InpRetryDelay);
            Sleep(InpRetryDelay);
        }
    }

    if(!all_data_ready)
    {
        Print("Failed to collect all required data");
        return "";
    }

    // Build feature array with corrected StringFormat
    for(int i = InpLookBack - 1; i >= 0; i--)
    {
        // Validate array bounds
        if(i >= ArraySize(rates) || i >= ArraySize(ema) || i >= ArraySize(macd_main) || 
           i >= ArraySize(rsi) || i >= ArraySize(stoch_k) || i >= ArraySize(atr_val))
        {
            PrintFormat("Array bounds error at index %d", i);
            return "";
        }
        
        double atr_perc = (rates[i].close > 0) ? (atr_val[i] / rates[i].close) * 100 : 0;
        
        // FIXED: Proper StringFormat with correct format specifiers
        string feature_set = StringFormat(
            "{ \"EMA_%d\":%.5f, \"MACD_%d_%d_%d\":%.5f, \"MACDh_%d_%d_%d\":%.5f, \"MACDs_%d_%d_%d\":%.5f, \"RSI_%d\":%.5f, \"STOCHk_%d_%d_%d\":%.5f, \"STOCHd_%d_%d_%d\":%.5f, \"ATRr_%d\":%.5f }",
            InpMAPeriod, ema[i],
            InpMACDFast, InpMACDSlow, InpMACDSignal, macd_main[i],
            InpMACDFast, InpMACDSlow, InpMACDSignal, macd_hist[i],
            InpMACDFast, InpMACDSlow, InpMACDSignal, macd_sig[i],
            InpRSIPeriod, rsi[i],
            InpStochK, InpStochD, InpStochSlowing, stoch_k[i],
            InpStochK, InpStochD, InpStochSlowing, stoch_d[i],
            InpATRPeriod, atr_perc
        );
        
        payload += feature_set;
        if(i > 0) payload += ",";
    }

    payload += "]}";
    
    // Validate payload size
    if(StringLen(payload) > 1000000)
    {
        Print("JSON payload too large");
        return "";
    }
    
    return payload;
}

//+------------------------------------------------------------------+
//| Calculate Lot Size based on risk                                 |
//+------------------------------------------------------------------+
double CalculateLotSize(double atr_value)
{
    double account_balance = AccountInfoDouble(ACCOUNT_BALANCE);
    double risk_amount = account_balance * InpRiskPerTrade;
    double sl_pips = atr_value * InpSLMultiplier;
    
    if(sl_pips <= 0 || risk_amount <= 0) return symbol.LotsMin();

    double tick_value = symbol.TickValue();
    if(tick_value <= 0) return symbol.LotsMin();
    
    double lot_size = risk_amount / (sl_pips * tick_value);
    
    lot_size = NormalizeDouble(lot_size, 2);
    lot_size = MathMax(symbol.LotsMin(), lot_size);
    lot_size = MathMin(symbol.LotsMax(), lot_size);
    
    return lot_size;
}

//+------------------------------------------------------------------+
//| Check for a new bar                                              |
//+------------------------------------------------------------------+
bool IsNewBar()
{
    datetime current_time = iTime(_Symbol, _Period, 0);
    if(lastBarTime != current_time)
    {
        lastBarTime = current_time;
        return true;
    }
    return false;
}

//+------------------------------------------------------------------+