
//+------------------------------------------------------------------+
//|         cnn_lstm_strategy_Optimized.mq5 - API Client               |
//|      Generated by ML Backtester Framework - Copyright 2025       |
//+------------------------------------------------------------------+
#property copyright "Copyright 2025, ML Backtester Framework"
#property link      "https://github.com/your_repo"
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>
#include <Trade\SymbolInfo.mqh>

//--- EA Inputs
input string InpApiEndpoint = "http://192.168.0.244:5001/predict"; // API Endpoint for predictions
input double InpRiskPerTrade = 0.01;      // Risk per trade
input double InpSLMultiplier = 2.5;    // Stop Loss ATR Multiplier
input double InpTPMultiplier = 3.5;    // Take Profit ATR Multiplier
input int    InpLookBack     = 96;      // Model Look-back period

//--- Indicator Parameters (must match training)
input int    InpMAPeriod     = 200;
input int    InpMACDFast     = 12;
input int    InpMACDSlow     = 26;
input int    InpMACDSignal   = 9;
input int    InpRSIPeriod    = 14;
input int    InpStochK       = 14;
input int    InpStochD       = 3;
input int    InpStochSlowing = 3;
input int    InpATRPeriod    = 14;

//--- Global Variables
CTrade      trade;
CSymbolInfo symbol;
datetime    lastBarTime = 0;
int         minBarsRequired;

//--- Indicator Handles
int ema_handle, macd_handle, rsi_handle, stoch_handle, atr_handle;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   symbol.Name(_Symbol);
   trade.SetExpertMagicNumber(67890);
   trade.SetMarginMode();

   //--- Calculate minimum bars required
   minBarsRequired = InpLookBack + 200;

   //--- Check for enough bars on chart
   if(Bars(_Symbol, _Period) < minBarsRequired)
     {
      printf("Not enough history on the chart. Required: %d, Available: %d", minBarsRequired, Bars(_Symbol, _Period));
      return(INIT_FAILED);
     }

   //--- Initialize all indicators needed for features
   ema_handle = iMA(_Symbol, _Period, InpMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   macd_handle = iMACD(_Symbol, _Period, InpMACDFast, InpMACDSlow, InpMACDSignal, PRICE_CLOSE);
   rsi_handle = iRSI(_Symbol, _Period, InpRSIPeriod, PRICE_CLOSE);
   stoch_handle = iStochastic(_Symbol, _Period, InpStochK, InpStochD, InpStochSlowing, MODE_SMA, STO_LOWHIGH);
   atr_handle = iATR(_Symbol, _Period, InpATRPeriod);

   if(ema_handle < 0 || macd_handle < 0 || rsi_handle < 0 || stoch_handle < 0 || atr_handle < 0)
     {
      printf("Error initializing one or more indicators.");
      return(INIT_FAILED);
     }
     
   Comment("CNN-LSTM EA Initialized. Waiting for new bar...");
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   IndicatorRelease(ema_handle);
   IndicatorRelease(macd_handle);
   IndicatorRelease(rsi_handle);
   IndicatorRelease(stoch_handle);
   IndicatorRelease(atr_handle);
   Comment("");
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(IsNewBar())
     {
      CheckForSignal();
     }
  }

//+------------------------------------------------------------------+
//| Check for a trading signal from the API                          |
//+------------------------------------------------------------------+
void CheckForSignal()
  {
   if(PositionsTotal() > 0) return; // Only trade if no open positions

   //--- Ensure we have enough bars for the look-back period + indicator warmup
   if(Bars(_Symbol, _Period) < minBarsRequired)
     {
      Comment("Not enough bars for look-back and indicator warmup.");
      return;
     }

   int signal = GetPrediction();

   if(signal == 0) return; // No signal or error

   double atr_val[];
   if(CopyBuffer(atr_handle, 0, 0, 1, atr_val) <= 0) return;
   
   double lot_size = CalculateLotSize(atr_val[0]);
   double sl=0, tp=0;

   if(signal == 1) // Buy Signal
     {
      sl = symbol.Ask() - atr_val[0] * InpSLMultiplier;
      tp = symbol.Ask() + atr_val[0] * InpTPMultiplier;
      trade.Buy(lot_size, _Symbol, symbol.Ask(), sl, tp, "CNN-LSTM Buy");
     }
   else if(signal == -1) // Sell Signal
     {
      sl = symbol.Bid() + atr_val[0] * InpSLMultiplier;
      tp = symbol.Bid() - atr_val[0] * InpTPMultiplier;
      trade.Sell(lot_size, _Symbol, symbol.Bid(), sl, tp, "CNN-LSTM Sell");
     }
  }

//+------------------------------------------------------------------+
//| Get prediction from Python API server                            |
//+------------------------------------------------------------------+
int GetPrediction()
  {
   string json_payload = BuildJsonPayload();
   if(json_payload == "") return 0;

   char post_data[], result_data[];
   string headers = "Content-Type: application/json\r\n";
   int timeout = 5000; // 5 seconds

   StringToCharArray(json_payload, post_data);

   ResetLastError();
   int res = WebRequest("POST", InpApiEndpoint, NULL, timeout, post_data, result_data, headers);

   if(res == -1)
     {
      printf("WebRequest failed. Error code: %d", GetLastError());
      return 0;
     }

   string result_str = CharArrayToString(result_data);
   
   //--- Simple JSON parsing to find the signal value
   int signal_pos = StringFind(result_str, "\"signal\":");
   if(signal_pos < 0)
     {
      printf("Could not find 'signal' in API response: %s", result_str);
      return 0;
     }
     
   string signal_substr = StringSubstr(result_str, signal_pos + 9); // 9 is len of "signal":
   int signal = (int)StringToInteger(StringSubstr(signal_substr, 0, StringFind(signal_substr, "}")));

   Comment("Received signal: " + (string)signal);
   return signal;
  }

//+------------------------------------------------------------------+
//| Build the JSON payload with feature data                         |
//+------------------------------------------------------------------+
string BuildJsonPayload()
  {
   string payload = "{\"features\": [";
   
   // Buffers for all features
   double ema[], macd_main[], macd_hist[], macd_sig[], rsi[], stoch_k[], stoch_d[], atr_val[];
   MqlRates rates[];

   // Copy data for the entire look_back period
   int data_to_copy = InpLookBack + 1;
   
   // Patiently check if data is ready. If not, abort and wait for the next tick.
   if(CopyBuffer(ema_handle, 0, 0, data_to_copy, ema) < data_to_copy ||
      CopyBuffer(macd_handle, 0, 0, data_to_copy, macd_main) < data_to_copy ||
      CopyBuffer(macd_handle, 2, 0, data_to_copy, macd_hist) < data_to_copy ||
      CopyBuffer(macd_handle, 1, 0, data_to_copy, macd_sig) < data_to_copy ||
      CopyBuffer(rsi_handle, 0, 0, data_to_copy, rsi) < data_to_copy ||
      CopyBuffer(stoch_handle, 0, 0, data_to_copy, stoch_k) < data_to_copy ||
      CopyBuffer(stoch_handle, 1, 0, data_to_copy, stoch_d) < data_to_copy ||
      CopyBuffer(atr_handle, 0, 0, data_to_copy, atr_val) < data_to_copy ||
      CopyRates(_Symbol, _Period, 0, data_to_copy, rates) < data_to_copy)
     {
      Comment("Indicator data not yet ready. Waiting for next tick.");
      return "";
     }

   for(int i = InpLookBack - 1; i >= 0; i--)
     {
      double atr_perc = (rates[i].close > 0) ? (atr_val[i] / rates[i].close) * 100 : 0;
      string feature_set = StringFormat(
          "{ \"EMA_d\":%.5f, \"MACD_d_d_d\":%.5f, \"MACDh_d_d_d\":%.5f, \"MACDs_d_d_d\":%.5f, \"RSI_d\":%.5f, \"STOCHk_d_d_d\":%.5f, \"STOCHd_d_d_d\":%.5f, \"ATRr_d\":%.5f }",
          InpMAPeriod, ema[i],
          InpMACDFast, InpMACDSlow, InpMACDSignal, macd_main[i],
          InpMACDFast, InpMACDSlow, InpMACDSignal, macd_hist[i],
          InpMACDFast, InpMACDSlow, InpMACDSignal, macd_sig[i],
          InpRSIPeriod, rsi[i],
          InpStochK, InpStochD, InpStochSlowing, stoch_k[i],
          InpStochK, InpStochD, InpStochSlowing, stoch_d[i],
          InpATRPeriod, atr_perc
      );
      payload += feature_set;
      if(i > 0) payload += ",";
     }

   payload += "]}";
   return payload;
  }

//+------------------------------------------------------------------+
//| Calculate Lot Size based on risk                                 |
//+------------------------------------------------------------------+
double CalculateLotSize(double atr_value)
  {
   double account_balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double risk_amount = account_balance * InpRiskPerTrade;
   double sl_pips = atr_value * InpSLMultiplier;
   if(sl_pips == 0) return 0.01;
   double tick_value = symbol.TickValue();
   double lot_size = risk_amount / (sl_pips * tick_value);
   lot_size = NormalizeDouble(lot_size, 2);
   if(lot_size < symbol.LotsMin()) lot_size = symbol.LotsMin();
   if(lot_size > symbol.LotsMax()) lot_size = symbol.LotsMax();
   return lot_size;
  }

//+------------------------------------------------------------------+
//| Check for a new bar                                              |
//+------------------------------------------------------------------+
bool IsNewBar()
  {
   datetime server_time = TimeCurrent();
   if(lastBarTime != iTime(_Symbol, _Period, 0))
     {
      lastBarTime = iTime(_Symbol, _Period, 0);
      return(true);
     }
   return(false);
  }
//+------------------------------------------------------------------+
