import logging
import platform
import socket
from typing import Dict, Any
from pathlib import Path

class ExportAgent:
    """
    Agent for exporting optimized strategies to different platforms.
    """

    def __init__(self, config: Dict[str, Any]):
        """
        Initializes the ExportAgent.

        Args:
            config (Dict[str, Any]): Configuration dictionary.
        """
        self.config = config
        self.export_path = Path(self.config.get('export', {}).get('path', 'ml_backtester/exports'))
        self.export_path.mkdir(exist_ok=True)
        logging.info(f"ExportAgent initialized. Export path: '{self.export_path}'")

    def execute(self, strategy_name: str, best_params: Dict[str, Any], backtest_results: Dict[str, Any]):
        """
        Executes the export process for the given strategy.

        Args:
            strategy_name (str): The name of the strategy to export.
            best_params (Dict[str, Any]): The best parameters found during optimization.
            backtest_results (Dict[str, Any]): The results from the final backtest run.
        """
        export_formats = self.config.get('export', {}).get('formats', [])
        if not export_formats:
            logging.warning("No export formats specified in the config. Skipping export.")
            return

        logging.info(f"Exporting strategy '{strategy_name}' with params: {best_params}")

        if 'mt5' in export_formats:
            self._export_to_mt5(strategy_name, best_params, backtest_results)

        if 'pinescript' in export_formats:
            self._export_to_pinescript(strategy_name, best_params, backtest_results)

    def _export_to_mt5(self, strategy_name: str, best_params: Dict[str, Any], backtest_results: Dict[str, Any]):
        """
        Exports the strategy to a MetaTrader 5 Expert Advisor (.mq5 file).
        """
        logging.info(f"Generating MT5 EA for '{strategy_name}'...")
        # Placeholder for MT5 export logic
        mt5_code = self._generate_mt5_code(strategy_name, best_params)
        file_path = self.export_path / f"{strategy_name}_optimized.mq5"
        with open(file_path, 'w') as f:
            f.write(mt5_code)
        logging.info(f"MT5 EA saved to '{file_path}'")

    def _export_to_pinescript(self, strategy_name: str, best_params: Dict[str, Any], backtest_results: Dict[str, Any]):
        """
        Exports the strategy to a TradingView PineScript (.pine file).
        """
        logging.info(f"Generating PineScript for '{strategy_name}'...")
        # Placeholder for PineScript export logic
        pinescript_code = self._generate_pinescript_code(strategy_name, best_params)
        file_path = self.export_path / f"{strategy_name}_optimized.pine"
        with open(file_path, 'w') as f:
            f.write(pinescript_code)
        logging.info(f"PineScript saved to '{file_path}'")

    def _generate_mt5_code(self, strategy_name: str, best_params: Dict[str, Any]) -> str:
        """
        Generates the MQL5 code for the strategy.
        This is a simplified placeholder. A real implementation would be more complex.
        """
        if strategy_name == 'triple_threat':
            return self._generate_mt5_for_triple_threat(strategy_name, best_params)
        elif strategy_name == 'bounce_back':
            return self._generate_mt5_for_bounce_back(strategy_name, best_params)
        elif strategy_name == 'cnn_lstm_strategy':
           return self._generate_mt5_for_cnn_lstm(strategy_name, best_params)
        else:
            return f"// Strategy '{strategy_name}' is not supported for MT5 export yet."

    def _generate_mt5_for_triple_threat(self, strategy_name: str, best_params: Dict[str, Any]) -> str:
        sl_multiplier = best_params.get('sl_atr_multiplier', 2.0)
        tp_multiplier = best_params.get('tp_atr_multiplier', 3.0)
        risk_per_trade = self.config.get('risk_management', {}).get('risk_per_trade', 0.01)

        return f"""
//+------------------------------------------------------------------+
//|                  {strategy_name}_Optimized.mq5                     |
//|      Generated by ML Backtester Framework - Copyright 2025       |
//+------------------------------------------------------------------+
#property copyright "Copyright 2025, ML Backtester Framework"
#property link      "https://github.com/your_repo"
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>
#include <Trade\SymbolInfo.mqh>

//--- Optimized Input Parameters
input double InpRiskPerTrade = {risk_per_trade};      // Risk per trade as a percentage of account balance
input double InpSLMultiplier = {sl_multiplier};    // Stop Loss ATR Multiplier
input double InpTPMultiplier = {tp_multiplier};    // Take Profit ATR Multiplier
input int    InpMAPeriod     = 200;      // EMA Period for Trend
input int    InpMACDFast     = 12;       // MACD Fast EMA
input int    InpMACDSlow     = 26;       // MACD Slow EMA
input int    InpMACDSignal   = 9;        // MACD Signal Line
input int    InpStochK       = 14;       // Stochastic %K
input int    InpStochD       = 3;        // Stochastic %D
input int    InpStochSlowing = 3;        // Stochastic Slowing
input int    InpATRPeriod    = 14;       // ATR Period for SL/TP

//--- Global Variables
CTrade      trade;
CSymbolInfo symbol;
datetime    lastBarTime = 0;

//--- Indicator Handles
int ema_handle;
int macd_handle;
int stoch_handle;
int atr_handle;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {{
   symbol.Name(_Symbol);
   trade.SetExpertMagicNumber(12345);
   trade.SetMarginMode();

   ema_handle = iMA(_Symbol, _Period, InpMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   macd_handle = iMACD(_Symbol, _Period, InpMACDFast, InpMACDSlow, InpMACDSignal, PRICE_CLOSE);
   stoch_handle = iStochastic(_Symbol, _Period, InpStochK, InpStochD, InpStochSlowing, MODE_SMA, STO_LOWHIGH);
   atr_handle = iATR(_Symbol, _Period, InpATRPeriod);

   if(ema_handle < 0 || macd_handle < 0 || stoch_handle < 0 || atr_handle < 0)
     {{
      printf("Error initializing indicators");
      return(INIT_FAILED);
     }}

   return(INIT_SUCCEEDED);
  }}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {{
   IndicatorRelease(ema_handle);
   IndicatorRelease(macd_handle);
   IndicatorRelease(stoch_handle);
   IndicatorRelease(atr_handle);
  }}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {{
   if(IsNewBar())
     {{
      CheckForSignal();
     }}
  }}

//+------------------------------------------------------------------+
//| Check for trading signals                                        |
//+------------------------------------------------------------------+
void CheckForSignal()
  {{
   // --- Get Indicator Values ---
   double ema[], macd_main[], macd_signal[], stoch_main[], stoch_signal[], atr[];
   if(CopyBuffer(ema_handle, 0, 1, 1, ema) <= 0 ||
      CopyBuffer(macd_handle, 0, 1, 2, macd_main) <= 0 ||
      CopyBuffer(macd_handle, 1, 1, 2, macd_signal) <= 0 ||
      CopyBuffer(stoch_handle, 0, 1, 2, stoch_main) <= 0 ||
      CopyBuffer(stoch_handle, 1, 1, 2, stoch_signal) <= 0 ||
      CopyBuffer(atr_handle, 0, 1, 1, atr) <= 0)
     {{
      printf("Error copying indicator buffers");
      return;
     }}

   MqlRates rates[2];
   if(CopyRates(_Symbol, _Period, 1, 2, rates) < 2) return;
   double current_close = rates[1].close;
   double prev_stoch_main = stoch_main[1];

   // --- Trading Conditions ---
   bool long_trend = current_close > ema[0];
   bool long_momentum = macd_main[0] > macd_signal[0];
   bool long_entry = stoch_main[0] > prev_stoch_main && prev_stoch_main < 20;

   bool short_trend = current_close < ema[0];
   bool short_momentum = macd_main[0] < macd_signal[0];
   bool short_entry = stoch_main[0] < prev_stoch_main && prev_stoch_main > 80;

   // --- Execution ---
   if(PositionsTotal() == 0)
     {{
      double lot_size = CalculateLotSize(atr[0]);
      double sl = 0, tp = 0;

      if(long_trend && long_momentum && long_entry)
        {{
         sl = symbol.Ask() - atr[0] * InpSLMultiplier;
         tp = symbol.Ask() + atr[0] * InpTPMultiplier;
         trade.Buy(lot_size, _Symbol, symbol.Ask(), sl, tp, "Buy Signal");
        }}
      else if(short_trend && short_momentum && short_entry)
        {{
         sl = symbol.Bid() + atr[0] * InpSLMultiplier;
         tp = symbol.Bid() - atr[0] * InpTPMultiplier;
         trade.Sell(lot_size, _Symbol, symbol.Bid(), sl, tp, "Sell Signal");
        }}
     }}
  }}

//+------------------------------------------------------------------+
//| Calculate Lot Size based on risk                                 |
//+------------------------------------------------------------------+
double CalculateLotSize(double atr_value)
  {{
   double account_balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double risk_amount = account_balance * InpRiskPerTrade;
   double sl_pips = atr_value * InpSLMultiplier;
   
   if(sl_pips == 0) return 0.01;

   double tick_value = symbol.TickValue();
   double lot_size = risk_amount / (sl_pips * tick_value);

   lot_size = NormalizeDouble(lot_size, 2);
   if(lot_size < symbol.LotsMin()) lot_size = symbol.LotsMin();
   if(lot_size > symbol.LotsMax()) lot_size = symbol.LotsMax();
   
   return lot_size;
  }}

//+------------------------------------------------------------------+
//| Check for a new bar                                              |
//+------------------------------------------------------------------+
bool IsNewBar()
  {{
   datetime server_time = TimeCurrent();
   if(lastBarTime != iTime(_Symbol, _Period, 0))
     {{
      lastBarTime = iTime(_Symbol, _Period, 0);
      return(true);
     }}
   return(false);
  }}
//+------------------------------------------------------------------+
"""

    def _generate_pinescript_code(self, strategy_name: str, best_params: Dict[str, Any]) -> str:
        """
        Generates the PineScript code for the strategy.
        This is a simplified placeholder.
        """
        if strategy_name == 'triple_threat':
            return self._generate_pinescript_for_triple_threat(strategy_name, best_params)
        elif strategy_name == 'bounce_back':
            return self._generate_pinescript_for_bounce_back(strategy_name, best_params)
        elif strategy_name == 'cnn_lstm_strategy':
            return self._generate_pinescript_for_cnn_lstm(strategy_name, best_params)
        else:
            return f"// Strategy '{strategy_name}' is not supported for PineScript export yet."

    def _generate_pinescript_for_triple_threat(self, strategy_name: str, best_params: Dict[str, Any]) -> str:
        sl_multiplier = best_params.get('sl_atr_multiplier', 2.0)
        tp_multiplier = best_params.get('tp_atr_multiplier', 3.0)

        return f"""
//@version=5
strategy("{strategy_name} Optimized", overlay=true, initial_capital=100000, default_qty_type=strategy.percent_of_equity, default_qty_value=1)

// --- Optimized Parameters ---
sl_atr_multiplier = input.float({sl_multiplier}, title="SL ATR Multiplier")
tp_atr_multiplier = input.float({tp_multiplier}, title="TP ATR Multiplier")
ema_len = input.int(200, title="EMA Length")
macd_fast = input.int(12, title="MACD Fast Length")
macd_slow = input.int(26, title="MACD Slow Length")
macd_signal = input.int(9, title="MACD Signal Length")
stoch_k = input.int(14, title="Stochastic %K")
stoch_d = input.int(3, title="Stochastic %D")
stoch_smooth = input.int(3, title="Stochastic Smoothing")
atr_len = input.int(14, title="ATR Length")

// --- Indicators ---
ema200 = ta.ema(close, ema_len)
[macd_line, signal_line, _] = ta.macd(close, macd_fast, macd_slow, macd_signal)
stoch_k_line = ta.sma(ta.stoch(close, high, low, stoch_k), stoch_smooth)
atr = ta.atr(atr_len)

// --- Plotting Indicators ---
plot(ema200, title="EMA 200", color=color.orange)

// --- Strategy Conditions ---
long_trend = close > ema200
long_momentum = macd_line > signal_line
long_entry = ta.crossover(stoch_k_line, 20)

short_trend = close < ema200
short_momentum = macd_line < signal_line
short_entry = ta.crossunder(stoch_k_line, 80)

// --- Execution Logic ---
if (long_trend and long_momentum and long_entry)
    sl = close - (atr * sl_atr_multiplier)
    tp = close + (atr * tp_atr_multiplier)
    strategy.entry("Long", strategy.long)
    strategy.exit("Long Exit", from_entry="Long", stop=sl, limit=tp)

if (short_trend and short_momentum and short_entry)
    sl = close + (atr * sl_atr_multiplier)
    tp = close - (atr * tp_atr_multiplier)
    strategy.entry("Short", strategy.short)
    strategy.exit("Short Exit", from_entry="Short", stop=sl, limit=tp)
"""

    def _generate_mt5_for_bounce_back(self, strategy_name: str, best_params: Dict[str, Any]) -> str:
        sl_multiplier = best_params.get('sl_atr_multiplier', 2.0)
        tp_multiplier = best_params.get('tp_atr_multiplier', 3.0)
        risk_per_trade = self.config.get('risk_management', {}).get('risk_per_trade', 0.01)
        fib_window = self.config.get('fib_window', 252)
        rsi_period = self.config.get('rsi_period', 14)

        return f"""
#property copyright "Copyright 2025, ML Backtester Framework"
#property link      "https://github.com/your_repo"
#property version   "1.00"

#include <Trade\Trade.mqh>

//--- Input Parameters
input double InpRiskPerTrade = {risk_per_trade};
input double InpSLMultiplier = {sl_multiplier};
input double InpTPMultiplier = {tp_multiplier};
input int    InpFibWindow    = {fib_window};
input int    InpRsiPeriod    = {rsi_period};
input int    InpATRPeriod    = 14;

CTrade trade;
datetime lastBarTime = 0;

int rsi_handle;
int atr_handle;

int OnInit() {{
    rsi_handle = iRSI(_Symbol, _Period, InpRsiPeriod, PRICE_CLOSE);
    atr_handle = iATR(_Symbol, _Period, InpATRPeriod);
    return(INIT_SUCCEEDED);
}}

void OnDeinit(const int reason) {{
    IndicatorRelease(rsi_handle);
    IndicatorRelease(atr_handle);
}}

void OnTick() {{
    if(IsNewBar()) {{
        CheckForSignal();
    }}
}}

void CheckForSignal() {{
    MqlRates rates[3];
    if(CopyRates(_Symbol, _Period, 0, 3, rates) < 3) return;

    double rsi_buffer[2];
    if(CopyBuffer(rsi_handle, 0, 1, 2, rsi_buffer) <= 0) return;

    double high_fib = High[iHighest(_Symbol, _Period, MODE_HIGH, InpFibWindow, 1)];
    double low_fib = Low[iLowest(_Symbol, _Period, MODE_LOW, InpFibWindow, 1)];
    double fib_50 = low_fib + 0.5 * (high_fib - low_fib);
    double fib_618 = low_fib + 0.618 * (high_fib - low_fib);

    bool is_bullish_engulfing = rates[1].close > rates[2].open && rates[1].open < rates[2].close && (rates[1].close - rates[1].open) > (rates[2].open - rates[2].close);
    bool is_bearish_engulfing = rates[1].open > rates[2].close && rates[1].close < rates[2].open && (rates[1].open - rates[1].close) > (rates[2].close - rates[2].open);
    
    bool bullish_divergence = rates[1].low < rates[2].low && rsi_buffer[0] > rsi_buffer[1];
    bool bearish_divergence = rates[1].high > rates[2].high && rsi_buffer[0] < rsi_buffer[1];

    bool at_support = rates[1].low <= fib_50 || rates[1].low <= fib_618;
    bool at_resistance = rates[1].high >= fib_50 || rates[1].high >= fib_618;

    double atr_val[1];
    CopyBuffer(atr_handle, 0, 0, 1, atr_val);

    if (at_support && is_bullish_engulfing && bullish_divergence) {{
        double sl = rates[1].close - atr_val[0] * InpSLMultiplier;
        double tp = rates[1].close + atr_val[0] * InpTPMultiplier;
        trade.Buy(CalculateLotSize(atr_val[0]), _Symbol, SymbolInfoDouble(_Symbol, SYMBOL_ASK), sl, tp);
    }}

    if (at_resistance && is_bearish_engulfing && bearish_divergence) {{
        double sl = rates[1].close + atr_val[0] * InpSLMultiplier;
        double tp = rates[1].close - atr_val[0] * InpTPMultiplier;
        trade.Sell(CalculateLotSize(atr_val[0]), _Symbol, SymbolInfoDouble(_Symbol, SYMBOL_BID), sl, tp);
    }}
}}

bool IsNewBar() {{
    datetime server_time = TimeCurrent();
    if(lastBarTime != iTime(_Symbol, _Period, 0)) {{
        lastBarTime = iTime(_Symbol, _Period, 0);
        return(true);
    }}
    return(false);
}}

double CalculateLotSize(double atr_value) {{
   double account_balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double risk_amount = account_balance * InpRiskPerTrade;
   double sl_pips = atr_value * InpSLMultiplier;
   if(sl_pips == 0) return 0.01;
   double tick_value = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double lot_size = risk_amount / (sl_pips * tick_value);
   lot_size = NormalizeDouble(lot_size, 2);
   if(lot_size < SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN)) lot_size = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   if(lot_size > SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX)) lot_size = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   return lot_size;
}}
"""

    def _generate_pinescript_for_bounce_back(self, best_params: Dict[str, Any]) -> str:
        sl_multiplier = best_params.get('sl_atr_multiplier', 2.0)
        tp_multiplier = best_params.get('tp_atr_multiplier', 3.0)
        fib_window = self.config.get('fib_window', 252)
        rsi_period = self.config.get('rsi_period', 14)

        return f"""
//@version=5
strategy("Bounce Back Optimized", overlay=true)

// --- Parameters ---
sl_atr_multiplier = input.float({sl_multiplier}, title="SL ATR Multiplier")
tp_atr_multiplier = input.float({tp_multiplier}, title="TP ATR Multiplier")
fib_window = input.int({fib_window}, title="Fibonacci Window")
rsi_period = input.int({rsi_period}, title="RSI Period")
atr_len = input.int(14, title="ATR Length")

// --- Indicators and Logic ---
rsi = ta.rsi(close, rsi_period)
atr = ta.atr(atr_len)

high_fib = ta.highest(high, fib_window)
low_fib = ta.lowest(low, fib_window)
fib_range = high_fib - low_fib
fib_50 = low_fib + 0.5 * fib_range
fib_618 = low_fib + 0.618 * fib_range

bullish_engulfing = close > open[1] and open < close[1] and (close - open) > (open[1] - close[1])
bearish_engulfing = open > close[1] and close < open[1] and (open - close) > (close[1] - open[1])

bullish_divergence = low < low[1] and rsi > rsi[1]
bearish_divergence = high > high[1] and rsi < rsi[1]

at_support = low <= fib_50 or low <= fib_618
at_resistance = high >= fib_50 or high >= fib_618

// --- Entry Conditions ---
long_signal = at_support and bullish_engulfing and bullish_divergence
short_signal = at_resistance and bearish_engulfing and bearish_divergence

if (long_signal)
    sl = close - (atr * sl_atr_multiplier)
    tp = close + (atr * tp_atr_multiplier)
    strategy.entry("Long", strategy.long)
    strategy.exit("Long Exit", from_entry="Long", stop=sl, limit=tp)

if (short_signal)
    sl = close + (atr * sl_atr_multiplier)
    tp = close - (atr * tp_atr_multiplier)
    strategy.entry("Short", strategy.short)
    strategy.exit("Short Exit", from_entry="Short", stop=sl, limit=tp)

// --- Plotting ---
plot(fib_50, "Fib 50.0", color=color.new(color.blue, 50))
plot(fib_618, "Fib 61.8", color=color.new(color.purple, 50))
"""

    def _generate_mt5_for_cnn_lstm(self, strategy_name: str, best_params: Dict[str, Any]) -> str:
        sl_multiplier = best_params.get('sl_atr_multiplier', 2.0)
        tp_multiplier = best_params.get('tp_atr_multiplier', 3.0)
        risk_per_trade = self.config.get('risk_management', {}).get('risk_per_trade', 0.01)
        look_back = self.config.get('modeling', {}).get('look_back', 60)

        api_endpoint = self._get_api_endpoint()
        return f"""
#property copyright "Copyright 2025, ML Backtester Framework"
#property version   "1.00"
#include <Trade\\Trade.mqh>

//--- Inputs
input string InpApiEndpoint = "{api_endpoint}";
input double InpRiskPerTrade = {risk_per_trade};
input double InpSLMultiplier = {sl_multiplier};
input double InpTPMultiplier = {tp_multiplier};
input int    InpLookback     = {look_back};
input int    InpATRPeriod    = 14;

CTrade trade;
datetime lastBarTime = 0;
int atr_handle;

int OnInit() {{
    atr_handle = iATR(_Symbol, _Period, InpATRPeriod);
    return(INIT_SUCCEEDED);
}}

void OnDeinit(const int reason) {{
    IndicatorRelease(atr_handle);
}}

void OnTick() {{
    if(IsNewBar()) {{
        int signal = GetSignalFromAPI();
        if(signal != 0) {{
            double atr_val[1];
            CopyBuffer(atr_handle, 0, 0, 1, atr_val);
            double sl = 0, tp = 0;
            if(signal == 1) {{
                sl = SymbolInfoDouble(_Symbol, SYMBOL_ASK) - atr_val[0] * InpSLMultiplier;
                tp = SymbolInfoDouble(_Symbol, SYMBOL_ASK) + atr_val[0] * InpTPMultiplier;
                trade.Buy(CalculateLotSize(atr_val[0]), _Symbol, SymbolInfoDouble(_Symbol, SYMBOL_ASK), sl, tp);
            }} else if(signal == -1) {{
                sl = SymbolInfoDouble(_Symbol, SYMBOL_BID) + atr_val[0] * InpSLMultiplier;
                tp = SymbolInfoDouble(_Symbol, SYMBOL_BID) - atr_val[0] * InpTPMultiplier;
                trade.Sell(CalculateLotSize(atr_val[0]), _Symbol, SymbolInfoDouble(_Symbol, SYMBOL_BID), sl, tp);
            }}
        }}
    }}
}}

int GetSignalFromAPI() {{
    char post[], result[];
    string headers = "Content-Type: application/json\\r\\n";
    MqlRates rates[];
    ArrayResize(rates, InpLookback);
    CopyRates(_Symbol, _Period, 1, InpLookback, rates);

    string json = "{{\\"features\\":[";
    for(int i=0; i<InpLookback; i++) {{
        json += "[";
        // This part is tricky and depends on the exact features the model was trained on.
        // We are sending OHLC as a placeholder.
        json += DoubleToString(rates[i].open) + ",";
        json += DoubleToString(rates[i].high) + ",";
        json += DoubleToString(rates[i].low) + ",";
        json += DoubleToString(rates[i].close);
        json += "]";
        if(i < InpLookback - 1) json += ",";
    }}
    json += "]}}";
    
    StringToCharArray(json, post);
    int res = WebRequest("POST", InpApiEndpoint, headers, 5000, post, result, headers);

    if(res == 200) {{
        // Simplified JSON parsing
        string result_str = CharArrayToString(result);
        if(StringFind(result_str, "\\"signal\\": 1") > 0) return 1;
        if(StringFind(result_str, "\\"signal\\": -1") > 0) return -1;
    }}
    return 0;
}}

bool IsNewBar() {{
    datetime server_time = TimeCurrent();
    if(lastBarTime != iTime(_Symbol, _Period, 0)) {{
        lastBarTime = iTime(_Symbol, _Period, 0);
        return(true);
    }}
    return(false);
}}

double CalculateLotSize(double atr_value) {{
   double account_balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double risk_amount = account_balance * InpRiskPerTrade;
   double sl_pips = atr_value * InpSLMultiplier;
   if(sl_pips == 0) return 0.01;
   double tick_value = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double lot_size = risk_amount / (sl_pips * tick_value);
   lot_size = NormalizeDouble(lot_size, 2);
   if(lot_size < SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN)) lot_size = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   if(lot_size > SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX)) lot_size = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   return lot_size;
}}
"""

    def _generate_pinescript_for_cnn_lstm(self, best_params: Dict[str, Any]) -> str:
        sl_multiplier = best_params.get('sl_atr_multiplier', 2.0)
        tp_multiplier = best_params.get('tp_atr_multiplier', 3.0)
        look_back = self.config.get('modeling', {}).get('look_back', 60)

        return f"""
//@version=5
strategy("CNN-LSTM API Strategy", overlay=true)

// --- Parameters ---
api_endpoint = input.string("http://127.0.0.1:5001/predict", title="API Endpoint")
sl_atr_multiplier = input.float({sl_multiplier}, title="SL ATR Multiplier")
tp_atr_multiplier = input.float({tp_multiplier}, title="TP ATR Multiplier")
look_back = input.int({look_back}, title="Look Back")
atr_len = input.int(14, title="ATR Length")

// --- Signal Logic ---
var signal = 0
if (barstate.isnew)
    // Construct the JSON payload
    // NOTE: This is a simplified example. A real implementation would need to gather
    // all the features the model was trained on.
    features_json = '['
    for i = 1 to look_back
        features_json += '[' + str.tostring(open[i]) + ',' + str.tostring(high[i]) + ',' + str.tostring(low[i]) + ',' + str.tostring(close[i]) + ']'
        if i < look_back
            features_json += ','
    features_json += ']'
    
    request_body = '{{ "features": ' + features_json + ' }}'
    
    // Send request to the API
    // Note: request.security with lookahead is needed to get future data for the API
    // This is a conceptual example; direct HTTP requests from PineScript have limitations.
    // A more robust solution might involve a webhook service.
    // For this example, we'll simulate a signal.
    // signal = request.post(api_endpoint, body=request_body)
    
    // Placeholder for signal, since direct request is complex
    if (close > open)
        signal := 1
    else
        signal := -1

// --- Execution ---
atr = ta.atr(atr_len)
if (signal == 1)
    sl = close - (atr * sl_atr_multiplier)
    tp = close + (atr * tp_atr_multiplier)
    strategy.entry("Long", strategy.long)
    strategy.exit("Long Exit", from_entry="Long", stop=sl, limit=tp)

if (signal == -1)
    sl = close + (atr * sl_atr_multiplier)
    tp = close - (atr * tp_atr_multiplier)
    strategy.entry("Short", strategy.short)
    strategy.exit("Short Exit", from_entry="Short", stop=sl, limit=tp)
"""